apps/bajas_semanales/api/v1/urls.py
from django.urls import path

from apps.bajas_semanales.api.v1.views import GetSelectsData, RecheckBaja


urlpatterns = [
    path('get_apps/', GetSelectsData.as_view(), name='get_apps'),
    path('recheck/', RecheckBaja.as_view(), name='recheck_baja'), #get/post
]

apps/tools/api/v1/urls.py
from django.urls import path

from apps.tools.api.v1.views import FileAPI


urlpatterns = [
    path('tools-api-v1/export', FileAPI.as_view(), name='download_file'),
]

apps/zendesk/api/v1/urls.py
from django.urls import path, include

from apps.zendesk.api.v1.views import GetActiveUsersAPI, ExportUserAPI, GetTickets, \
    StructureTicket


urlpatterns = [
    path('user/users', GetActiveUsersAPI.as_view(), name='get_users'),
    path('user/export', ExportUserAPI.as_view(), name='export_users'),
    path('ticket/tickets', GetTickets.as_view(), name='tickets'),
    path('ticket/structure', StructureTicket.as_view(), name='structure'),
]

apps/zendesk/urls.py
from django.urls import path, include

from apps.zendesk.views import Zendesk

urlpatterns = [
    path('active_users', Zendesk.as_view(), name='active_users'),
    
]

voi/urls.py
from django.contrib import admin
from django.contrib.auth import authenticate

from django.urls import path, include

from django.apps import apps

from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import View

from braces.views import LoginRequiredMixin

from apps.tools.mixins import NeverCacheMixin, CSRFExemptMixin


application = apps.get_app_config('application').verbose_name
user = apps.get_app_config('user').verbose_name
bi_modules = apps.get_app_config('bi_modules').verbose_name
bajas_semanales = apps.get_app_config('bajas_semanales').verbose_name
zendesk = apps.get_app_config('zendesk').verbose_name
tools = apps.get_app_config('tools').verbose_name



class Dashboard(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, View):

    def get(self, request):
        #user = request.user
        context = {}
        context['dashboard'] = True
        return render(request, 'index.html', context)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('application/', include(('apps.application.urls', application), namespace='application')),
    path('bi_modules/', include(('apps.bi_modules.urls', bi_modules), namespace='bi_modules')),
    path('bajas/', include(('apps.bajas_semanales.urls', bajas_semanales), namespace='bajas_semanales')),
    path('zendesk/', include(('apps.zendesk.urls', zendesk), namespace='zendesk')),
    path('tools/', include(('apps.tools.urls', zendesk), namespace='tools')),

    path('api-auth/', include('rest_framework.urls')),
    path('bajas_semanales-api-v1/', include(('apps.bajas_semanales.api.v1.urls', bajas_semanales), namespace='bajas-semanales-api-v1')),
    path('bi_modules-api-v1/', include(('apps.bi_modules.api.v1.urls', bi_modules), namespace='bi_modules-api-v1')),
    path('zendesk-api-v1/', include(('apps.zendesk.api.v1.urls', zendesk), namespace='zendesk-api-v1')),
    path('tools-api-v1/', include(('apps.tools.api.v1.urls', tools), namespace='tools-api-v1')),
] + static(settings.STATIC_URL,
    document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

apps/zendesk/api/v1/views.py
import sys, os

from datetime import datetime

from django.db import transaction

from django.contrib.auth.models import User

from rest_framework.views import APIView
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from dotenv import load_dotenv

import pandas as pd

from apps.zendesk.models import ZendeskUser

from apps.tools.http.services import GetAPI, GetZendeskUser, UserGroup
from apps.tools.views import File
from apps.tools.mixins import LoginRequiredMixin, NeverCacheMixin
from apps.zendesk.models import ZendeskUser, ZendeskUserHistory

load_dotenv()


now = datetime.now()

class GetActiveUsersAPI(LoginRequiredMixin, NeverCacheMixin, APIView):

    """Get the active users lists only in json format."""

    authentication_classes = [ SessionAuthentication, BasicAuthentication ]
    permission_classes = [ IsAuthenticated ]

    @transaction.atomic
    def get(self, request):
        data = {}
        hist = None
        domain = os.getenv('ZENDESK_API_DOMAIN')
        path = os.getenv('ZENDESK_USER_API')
        api_filter_query = os.getenv('ZENDESK_USER_FILTER')
        final_user_list = None
        try:
            data_api = GetAPI(domain, path, api_filter=api_filter_query)
            json_response = data_api.get()
            get_user = GetZendeskUser(json_response)
            print('Getting User List . . .')
            user_list = get_user.get_user()

            print('Getting User Groups . . .')
            user_group = UserGroup(user_list, domain)
            final_user_list = user_group.get_user_group()
            
            hist = self.create_hist(final_user_list)
            for u in final_user_list:
                group = str(u['group(s)']).replace('[', '').replace("'", "").replace("]", "")
                zendeskUser = ZendeskUser(
                    user_id=u['id'],
                    name=u['name'],
                    email=u['email'],
                    role=u['role'],
                    group=group,
                    hist=ZendeskUserHistory.objects.get(id=hist.id)
                )
                zendeskUser.save()
            filename = 'Active_Zendesk_usesrs_' + \
                datetime.now().strftime('%d-%m-%Y - %H.%m.%s')

            data['filename'] = filename + '.csv'
            data['total_occupied'] = hist.total_occupied_licenses
            data['current_admins'] = hist.current_admins
            data['current_agents'] = hist.current_agents
            data['success'] = True
            data['message'] = final_user_list
            data['status_code'] = '200'
        except Exception as t:
            data['message'] = t
            print('Error trying to retrieve API: ', str(t))
        return Response(data)
    def create_hist(self, user_list):
        try:
            total_licenses = len(user_list)
            total_admins = []
            total_agents = []
            for u in user_list:
                for i in u.values():
                    total_admins.append( i if i == 'admin' else None )
                    total_agents.append( i if i == 'agent' else None )
            total_agents = [len(a) for a in total_agents if a == 'agent']
            total_admins = [len(a) for a in total_admins if a == 'admin']

            zendesk_hist = ZendeskUserHistory(
                total_occupied_licenses=total_licenses,
                current_admins=str(len(total_admins)),
                current_agents=str(len(total_agents)),
                exec_user=User.objects.get(id=self.request.user.id)
            )
            zendesk_hist.save()

            return zendesk_hist
        except Exception as g:
            print('Error trying to create History: ', g)
            return g


class ExportUserAPI(LoginRequiredMixin, NeverCacheMixin, APIView):

    """ Export zendesk users data into a *csv file, in a subfolder allocated in the default 
        media project. """

    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request):
        data = {}
        final_user_list = []
        try:
            user_history = ZendeskUserHistory.objects.last()
            user_list = ZendeskUser.objects.filter(hist=user_history.id)
            c = 1
            for u in user_list:
                final_user_list.append({
                    'Name': u.name,
                    'Email': u.email,
                    'Role': u.role,
                    'Group(s)': u.group
                })
                c = c + 1

            filename = self.request.GET.get('filename')
            filepath = os.path.dirname(os.path.abspath('voi/')) + '/voi/media/user_files/'
            # Trigger the generation and file download for user purposes.
            export = File(filepath, filename)
            export.exportToFile(user_list=final_user_list)
            
            data['success'] = True
            data['message'] = 'File exported Successfully!'
        except Exception as f:
            data['message'] = str(f)
            print('Exc: ', f)
        return Response(data)


class GetTickets(LoginRequiredMixin, NeverCacheMixin, APIView):

    """Return All tickets from a date range."""

    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request):

        domain = os.getenv('ZENDESK_API_DOMAIN')
        path = os.getenv('ZENDESK_TICKET_API')
        filter_query = os.getenv('ZENDESK_TICKET_FILTER')

        try:
            data = {}
            data_api = GetAPI(domain, path, filter_query)
            json_response = data_api.get()

            ticket_list = []
            for item in json_response:
                # Getting Ticket list only, from incremental API
                for t in item['tickets']:
                    ticket_list.append(t)
            filename = 'Zendesk_tickets_' + \
                datetime.now().strftime('%d-%m-%Y - %H.%m.%s')
            filepath = os.path.dirname(os.path.abspath('user_files/')) + \
                '/zendesk_tickets/unstructured_datasets/'
            file_type = '.csv'
            export = File(filepath, file_type)
            export.exportToFile(created_at=ticket_list, filename=filename)

            data['tickets'] = 'Number of total items in List: ', len(ticket_list)
            data['success'] = True
        except Exception as g:
            print('Error: ', str(g))
            data['message'] = str(g)
        return Response(data)


class StructureTicket(LoginRequiredMixin, NeverCacheMixin, APIView):

    """
    API that get all unstructured datasets outputs from 
    "GetTickets()", build an entire DataFRame and 
    separate every desired dataset in dataframes.
    It create a new file for each month \nEg. Enero-2020 , Febrero2020, etc.\n
    This function needs to be called every time when a new dataFrame needs to be
    created for future processes.\n

    For this execution, datasets needs to be in the folder: /zendesk_tickets/.
    """

    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request):
        data = {}
        return Response(data)
    def buildDataFrame(self):
        """
        Get data into a list form 
        """
        path = os.path.dirname(os.path.abspath('user_files/')) + \
            '/zendesk_tickets/unstructured_datasets/' 
        file_format = '*csv'
        getFile = File(path + file_format)
        file_list = getFile.getFile()

        data_list = []
        c = 1
        for f in file_list:
            print('#', c)
            df = pd.read_csv(f, index_col=None, header=0)
            data_list.append(df)
            c += 1
        df = pd.concat(data_list, axis=0, ignore_index=True)
        print('DF head: \n', df.head())
        return df

    def post(self, request):

        data = {}
        print('Building DataFrame. .  .')
        data_df = self.buildDataFrame()
        months = {
            'Enero|': '2020-01',
            'Febrero': '2020-02',
            'Marzo': '2020-03',
            'Abril': '2020-04',
            'Mayo': '2020-05',
            'Junio': '2020-06',
            'Julio': '2020-07',
            'Agosto': '2020-08',
            'Septiembre': '2020-09',
            'Octubre': '2020-10',
            'Noviembre': '2020-11' ,
            'Diciembre': '2020-12'
        }
        c = 1
        for k, v in months.items():
            try:
                created_at_df = data_df[data_df['created_at'].str.contains(months[k], na=False)]
                current_yearmonth = k.replace('|', '') + v[:-3]
                filename = str(c) + '_ZendeskTickets-' + current_yearmonth

                # Quitar. Se repite en línea #196.
                path = '/Users/isaialejandro/Documents/workSpace/Django/voireg/voi_app/zendesk_tickets/final_data/'
                file = File(path)
                file.exportToFile(created_at=created_at_df, filename=filename)
                c += 1
            except Exception as x:
                print('ERROR: ', x)
                sys.exit(1)
        data['success'] = 'All files exported successfully!!'
        return Response(data)   

apps/zendesk/views.py
from django.shortcuts import render

from apps.zendesk.models import ZendeskUserHistory, ZendeskUser
from django.views.generic.list import ListView

from apps.tools.mixins import LoginRequiredMixin, NeverCacheMixin, \
    PermissionRequiredMixin, CSRFExemptMixin

class Zendesk(LoginRequiredMixin, NeverCacheMixin, \
                CSRFExemptMixin, ListView):

    model = ZendeskUser
    template_name = 'active_user_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #context['active_users'] = True
        return context

apps/zendesk/templates/active_user_list.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Bajas Semanales
{% endblock %}

{% block extracss %}
  <link href="{% static 'css/plugins/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet">
  <link href="{% static 'css/animate.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- Ladda style -->
  <link href="{% static 'css/plugins/ladda/ladda-themeless.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Widgets</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li class="active">
                    <strong>Widgets</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
      <div class="row">
          <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Get Active <small>Zendesk Useres</small></h5>
                </div>
                <div class="ibox-content">
                    <div class="text-center">
                      <button class="ladda-button ladda-button-demo btn btn-primary" id="get_data" data-style="zoom-in">Get users</button>
                    </div>
                    <form method="post" action="#">
                      {% csrf_token %}
                      <div class="text-center">
                        <a class="btn btn-success" id='export_file' download="userfile" disabled="disabled" data-href="#">Export </a>
                      </div>  
                    </form>
                </div>
            </div>
          </div>

        <div class="col-lg-2">
            <div class="widget navy-bg p-lg text-center">
                <div class="m-b-md">
                    <i class="fa fa-users fa-4x"></i>
                    <h1 class="m-xs" id="users_no">xx</h1>
                    <small>Active</small>
                    <h3 class="font-bold no-margins">
                        Users
                    </h3>
                </div>
            </div>
        </div>

        <div class="col-lg-2">
            <div class="widget yellow-bg p-lg text-center">
                <div class="m-b-md">
                    <i class="fa fa-shield fa-4x"></i>
                    <h1 class="m-xs" id="agents_no">xx</h1>
                    <small>Active</small>
                    <h3 class="font-bold no-margins">
                        Agents
                    </h3>
                </div>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="widget red-bg p-lg text-center">
                <div class="m-b-md">
                    <i class="fa fa-gear fa-4x"></i>
                    <h1 class="m-xs" id="admins_no">xx</h1>
                    <small>Active</small>
                    <h3 class="font-bold no-margins">
                        Admins
                    </h3>
                </div>
            </div>
        </div>
      </div>

    </div>

{% endblock %}

{% block extrajs %}
    <!-- Ladda -->
    <script src="{% static 'js/plugins/ladda/spin.min.js' %}"></script>
    <script src="{% static 'js/plugins/ladda/ladda.min.js' %}"></script>
    <script src="{% static 'js/plugins/ladda/ladda.jquery.min.js' %}"></script>

    <script>

        $(document).ready(function(){
          
          var get_data = $('#get_data');
          var export_btn = $('#export_btn');
          var users_number = $('#users_no');
          var agents_number = $('#agents_no');
          var admins_number = $('#admins_no');
          var end_users_number = $('#end_users_no');
          var l = $( '.ladda-button-demo' ).ladda();
          //var export_file = $('#export_file');
          var current_filename = '';

          users_number.empty().html('- -');
          agents_number.empty().html('- -');
          admins_number.empty().html('- -');
          end_users_number.empty().html('- -');

          var cookie = document.cookie
          var csrfToken = cookie.substring(cookie.indexOf('=') + 1)
          
          get_data.click(function() { //Get users button
            $('#export_file').attr('disabled', true);
            l.ladda( 'start' );
            $.ajax({
              url: '{% url "zendesk-api-v1:get_users" %}',
              method: 'get',
              dataType: 'json',
              success: function(data) {
                console.log('Getting user list . . . ');
                if(data.success) {
                  console.log('User list obtanied successfully.');
                  current_filename = data.filename;

                  users_number.empty().html(data.total_occupied);
                  agents_number.empty().html(data.current_agents);
                  admins_number.empty().html(data.current_admins);
                  end_users_number.empty().html('x');
                  l.ladda( 'stop' );
                  //$('#export_file').prop('disabled', false);
                  $('#export_file').removeAttr('disabled')
                  $('#export_file').empty().html('Export ' + current_filename + ' to a file');
                  
                }
                else {
                  console.log('Error, something happened. Else: \n', data.responseJSON['detail']);
                  l.ladda( 'stop' );  
                }
              },
              error: function(data) {
                console.log('Error, something happened: \n', data);
                l.ladda( 'stop' );
              },
            });
          });

          //User list to API
          $('#export_file').click(function(){ 
            console.log('Current filename: ', current_filename);
            get_data.prop('disabled', 'disabled')
            //e.preventDefault();
            $.ajax({
              url: '{% url "zendesk-api-v1:export_users" %}',
              method: 'GET',
              dataType: 'json',
              /*headers: {
                'X-CSRFToken': csrfToken
              },*/
              data: {
                'filename': current_filename,
              },
              success: function(data) {
                if (data.success) {
                  window.location.href = "/tools-api-v1/tools-api-v1/export?filename=" + current_filename;
                  alert(data.message);
                }
              },
              error: function(data){
                alert(data.message);
              },
            });
          });

          /*$('#download_file').click(function(){
            $.ajax({
              url: "", //{% url 'tools-api-v1:download_file' %}
              dataType: 'json',
              method: 'GET',
              data: {
                filename: current_filename
              },
              success: function(data){
                console.log('Data: ', data);
              },
              error: function(data){
                console.log(data.error);
              },
            });
          });*/

          /* CSRF Token */
          function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        /* CSRF Token */
        const csrftoken = getCookie('csrftoken');


          /*ladda-button-demo.click(function(){
          });*/



          //GET BAJASEMANAL IN MODAL
          /*btn_update.on('click', function(){
            var id = $(this).data("id");
            //Passing id record to Save Changes modal btn for post method.
            btn_modal_save.data('id', id)

            $.ajax({
              url: "{% url 'bajas-semanales-api-v1:recheck_baja' %}",
              dataType: 'json',
              method: 'get',
              data: {
                "id": id
              },
              success: function(data){
                if(data.success){

                  $.each(data.baja_semanal, function(index, item){
                    modal_title.empty().html(item.type);
                    modal_little_desc.empty().html(item.subject);


                    subject_input.empty().val(item.subject);
                    user_code_input.empty().val(item.user_code);
                    user_name_input.empty().val(item.user_name);
                    request_date_input.empty().val(item.request_date);
                  });

                  s_type.empty();
                  $.each(data.tipo_bajas, function(index, item){
                    if(item.selected == true){
                      s_type.append('<option value="'+ item.id +'" selected="selected">'+ item.text +'</option>');
                    } else {
                      s_type.append('<option value="'+ item.id +'">'+ item.text +'</option>');
                    }
                  });

                  s_app.empty().trigger("change");
                  $.each(data.results, function(index, item){

                     if(item.selected == true){
                         var newOption = new Option(item.text, item.id, true, true);
                         s_app.append(newOption).trigger('change');
                     }
                     if(item.selected == false){
                       var newOption = new Option(item.text, item.id, false, false);
                       s_app.append(newOption);
                     }
                  });

                  modal_update.modal('show');
                } else {
                  console.log('Msg: ', data.message);
                }
              },
              error: function(data){
                console.log('Error to try to get recheck data modal: ', data);
              }
            });
          });

          modal_update.on('show.bs.modal', function() {
            s_app.select2({dropdownParent: modal_update});
            console.log('show');
          })
          modal_update.on('hidden.bs.modal', function() {
            s_app.select2('destroy');
          })
          */
        });
    </script>
{% endblock %}