apps/bajas_semanales/urls.py
from django.urls import path

from apps.bajas_semanales.views import TipoBajaList, CreateTipoBaja, BajasSemanalesList, CreateBajaSemanal


urlpatterns = [
    path('tipo_bajas_list/', TipoBajaList.as_view(), name='tipo_bajas_list'),
    path('create_tipo_baja/', CreateTipoBaja.as_view(), name='create_tipo_baja'),
    path('list/', BajasSemanalesList.as_view(), name='bajas_semanales_list'),
    path('new/', CreateBajaSemanal.as_view(), name='new'),
   #path('update/<int:pk>/', UpdateBaja.as_view(), name='update'),

]

apps/bi_modules/urls.py
from django.urls import path

from apps.bi_modules.views import IngresosYCuentasPorCobrarView

urlpatterns = [
    path('cuentas_por_cobrar/', IngresosYCuentasPorCobrarView.as_view(), name='cuentas_por_cobrar_dashboard'),
    #path(),
    #path(),

]

apps/user/urls.py
from django.contrib import admin
from django.contrib.auth import authenticate
from django.contrib.auth.models import Permission, User

from django.urls import path, include

from apps.user.views import UserList, CreateUser, UpdateUser#, PermissionsList, CreatePermission, UpdatePermission, DeletePermission, \
							#ProfileList, CreateProfile, UpdateProfile, DeleteProfile


urlpatterns = [
	path('list/', UserList.as_view(), name='list'),
	path('new/', CreateUser.as_view(), name='new'),
	path('update/<int:pk>', UpdateUser.as_view(), name='update_user'), #update & disable user.

	
]

"""
	path('permissions/', PermissionsList.as_view(), name='permissions'),
	path('create/', CreatePermission.as_view(), name='permissions'),
	path('update/<int:pk>', UpdatePermission.as_view(), name='create_permission'),
	path('delete_permission/', DeletePermission.as_view(), name='delete_permission'),

	path('list/', ProfileList.as_view(), name='profiles'),
	path('create/', CreateProfile.as_view(), name='create_profile'),
	path('update/<int:pk>', UpdateProfile.as_view(), name='update_profile'),
	path('delete/<int:pk>', DeleteProfile.as_view(), name='delete_profile'),
	"""

apps/zendesk/urls.py
from django.urls import path, include

from apps.zendesk.views import Zendesk

urlpatterns = [
    path('active_users', Zendesk.as_view(), name='active_users'),
    
]

voi/urls.py
from django.contrib import admin
from django.contrib.auth import authenticate

from django.urls import path, include

from django.apps import apps

from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import View

from braces.views import LoginRequiredMixin

from apps.tools.mixins import NeverCacheMixin, CSRFExemptMixin


application = apps.get_app_config('application').verbose_name
user = apps.get_app_config('user').verbose_name
bi_modules = apps.get_app_config('bi_modules').verbose_name
bajas_semanales = apps.get_app_config('bajas_semanales').verbose_name
zendesk = apps.get_app_config('zendesk').verbose_name
tools = apps.get_app_config('tools').verbose_name



class Dashboard(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, View):

    def get(self, request):
        #user = request.user
        context = {}
        context['dashboard'] = True
        return render(request, 'index.html', context)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('application/', include(('apps.application.urls', application), namespace='application')),
    path('bi_modules/', include(('apps.bi_modules.urls', bi_modules), namespace='bi_modules')),
    path('bajas/', include(('apps.bajas_semanales.urls', bajas_semanales), namespace='bajas_semanales')),
    path('zendesk/', include(('apps.zendesk.urls', zendesk), namespace='zendesk')),
    path('tools/', include(('apps.tools.urls', zendesk), namespace='tools')),

    path('api-auth/', include('rest_framework.urls')),
    path('bajas_semanales-api-v1/', include(('apps.bajas_semanales.api.v1.urls', bajas_semanales), namespace='bajas-semanales-api-v1')),
    path('bi_modules-api-v1/', include(('apps.bi_modules.api.v1.urls', bi_modules), namespace='bi_modules-api-v1')),
    path('zendesk-api-v1/', include(('apps.zendesk.api.v1.urls', zendesk), namespace='zendesk-api-v1')),
    path('tools-api-v1/', include(('apps.tools.api.v1.urls', tools), namespace='tools-api-v1')),
] + static(settings.STATIC_URL,
    document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

voi/templates/index.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Dashboard
{% endblock %}

{% block extracss %}
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInUp">
        <div class="container">



        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script>
        $(document).ready(function(){

        });
    </script>
{% endblock %}

voi/templates/navbar.html
{% if user.is_authenticated %}

    <div class="row border-bottom white-bg">
        <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-header">
                <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <i class="fa fa-reorder"></i>
                </button>
                    <a
                    {% if not dashboard %}
                        href="{% url 'dashboard' %}"
                    {% else %}
                        href="#"
                    {% endif %}
                    class="navbar-brand">VOIRegistry</a>
            </div>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav">

                    {% if perms.zendesk.view_active_zendesk_user_list or perms.zendesk.get_active_zendesk_user_list %}
                        <li class="dropdown">
                            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Zendesk <span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                {% if perms.zendesk.view_active_zendesk_user_list %}
                                  {% if not active_users_hist %}
                                    <li><a href="{% url 'zendesk:active_users' %}">Active users Hist</a></li>
                                  {% endif %}       
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}

                    {% if perms.application.view_application_list or perms.application.create_application %}
                        <li class="dropdown">
                            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Application <span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                {% if perms.application.view_application_list %}
                                  {% if not app_list %}
                                    <li><a href="{% url 'application:list' %}">List</a></li>
                                  {% endif %}
                                  {% if perms.application.create_application %}
                                    {% if not new_app %}
                                        <li><a href="{% url 'application:new' %}">New Application</a></li>
                                    {% endif %}
                                  {% endif %}
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}

                    {% if perms.bajas_semanales.view_bajas_semanales_list or perms.bajas_semanales.create_baja_semanal or perms.bajas_semanales.view_tipo_bajas_list  %}
                        <li class="dropdown">
                            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Bajas Semanales <span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">

                                {% if perms.bajas_semanales.view_tipo_bajas_list %}
                                    {% if not tipo_bajas_list %}
                                        <li><a href="{% url 'bajas_semanales:tipo_bajas_list' %}">Tipo de Bajas - List</a></li>
                                    {% endif %}
                                {% endif %}

                                {% if perms.bajas_semanales.create_tipo_baja %}
                                    {% if not new_tipo_baja %}
                                        <li><a href="{% url 'bajas_semanales:create_tipo_baja' %}">New Tipo de Baja</a></li>
                                    {% endif %}
                                {% endif %}

                                {% if perms.bajas_semanales.view_bajas_semanales_list %}
                                    {% if not bajas_semanales_list %}
                                        <li><a href="{% url 'bajas_semanales:bajas_semanales_list' %}">Bajas Semanales - List</a></li>
                                    {% endif %}
                                {% endif %}
                                {% if perms.bajas_semanales.create_baja_semanal %}
                                    {% if not new_baja_semanal %}
                                        <li>
                                            <a href="{% url 'bajas_semanales:new' %}">New Baja Semanal</a>
                                        </li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}

                    {% if perms.bi_modules.view_cuentas_por_cobrar or perms.process_cuentas_por_cobrar %}
                        <li class="dropdown">
                            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> BI <span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                {% if perms.bi_modules.view_cuentas_por_cobrar %}
                                <li><a href="{% url 'bi_modules:cuentas_por_cobrar_dashboard' %}">Cuentas por Cobrar</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}

                    {% if user.is_superuser %}
                        <li class="dropdown">
                            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Users <span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="#" onclick="InProgress();";>User List</a></li>
                                  <li>
                                      <a href="#" onclick="InProgress();">Add new User</a>
                                  </li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Import/Export <span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="#" onclick="InProgress();">Users</a></li>
                                <li>
                                    <a href="#" onclick="InProgress();">Applications</a>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <span class="m-r-sm text-muted welcome-message">
                            Welcome,
                            <strong>
                            {% if user.username %}
                                {{ user.username}}.
                            {% elif user.first_name %}
                                {{ user.first_name}}.
                            {% endif %}
                            </strong>
                        </span>
                    </li>
                    Last login -
                    {{user.last_login}}
                    <li>
                        <a href="{% url 'logout' %}">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

{% endif %}

  <script type="text/javascript">
    function InProgress(){
      alert("In progress");
    }
  </script>