apps/bajas_semanales/api/v1/urls.py
from django.urls import path

from apps.bajas_semanales.api.v1.views import GetSelectsData, RecheckBaja


urlpatterns = [
    path('get_apps/', GetSelectsData.as_view(), name='get_apps'),
    path('recheck/', RecheckBaja.as_view(), name='recheck_baja'), #get/post
]

apps/bajas_semanales/urls.py
from django.urls import path

from apps.bajas_semanales.views import TipoBajaList, CreateTipoBaja, BajasSemanalesList, CreateBajaSemanal


urlpatterns = [
    path('tipo_bajas_list/', TipoBajaList.as_view(), name='tipo_bajas_list'),
    path('create_tipo_baja/', CreateTipoBaja.as_view(), name='create_tipo_baja'),
    path('list/', BajasSemanalesList.as_view(), name='bajas_semanales_list'),
    path('new/', CreateBajaSemanal.as_view(), name='new'),
   #path('update/<int:pk>/', UpdateBaja.as_view(), name='update'),

]

voi/urls.py
from django.contrib import admin
from django.contrib.auth import authenticate

from django.urls import path, include

from django.apps import apps

from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import View

from braces.views import LoginRequiredMixin

from apps.tools.mixins import NeverCacheMixin, CSRFExemptMixin


application = apps.get_app_config('application').verbose_name
user = apps.get_app_config('user').verbose_name
bi_modules = apps.get_app_config('bi_modules').verbose_name
bajas_semanales = apps.get_app_config('bajas_semanales').verbose_name
zendesk = apps.get_app_config('zendesk').verbose_name
tools = apps.get_app_config('tools').verbose_name



class Dashboard(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, View):

    def get(self, request):
        #user = request.user
        context = {}
        context['dashboard'] = True
        return render(request, 'index.html', context)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('application/', include(('apps.application.urls', application), namespace='application')),
    path('bi_modules/', include(('apps.bi_modules.urls', bi_modules), namespace='bi_modules')),
    path('bajas/', include(('apps.bajas_semanales.urls', bajas_semanales), namespace='bajas_semanales')),
    path('zendesk/', include(('apps.zendesk.urls', zendesk), namespace='zendesk')),
    path('tools/', include(('apps.tools.urls', zendesk), namespace='tools')),

    path('api-auth/', include('rest_framework.urls')),
    path('bajas_semanales-api-v1/', include(('apps.bajas_semanales.api.v1.urls', bajas_semanales), namespace='bajas-semanales-api-v1')),
    path('bi_modules-api-v1/', include(('apps.bi_modules.api.v1.urls', bi_modules), namespace='bi_modules-api-v1')),
    path('zendesk-api-v1/', include(('apps.zendesk.api.v1.urls', zendesk), namespace='zendesk-api-v1')),
    path('tools-api-v1/', include(('apps.tools.api.v1.urls', tools), namespace='tools-api-v1')),
] + static(settings.STATIC_URL,
    document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

apps/bajas_semanales/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from apps.application.models import Application


now = timezone.now


class TipoBaja(models.Model):

    type = models.CharField(max_length=100, blank=False, null=False)
    created_date = models.DateTimeField(default=now)
    is_active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)

    def __str__(self):
        return self.type

    class Meta:
        permissions = (
            ('view_tipo_bajas_list', 'Visualize Tipo de Bajas List'),
            ('create_tipo_baja', 'Create Tipo Baja'),
            ('update_tipo_baja', 'Update Tipo de Baja'),
            ('deactivate_tipo_baja', 'Deactivate Tipo de Baja'),
        )


class BajaSemanal(models.Model):

    uid = models.CharField(max_length=100, null=True, blank=True)
    type = models.ForeignKey('TipoBaja', on_delete=models.DO_NOTHING)
    subject = models.CharField(max_length=200, blank=False, null=False)
    user_code = models.CharField(max_length=20, blank=False, null=False)
    user_name = models.CharField(max_length=50, blank=False, null=False)
    request_date = models.DateField(max_length=10)
    application = models.ManyToManyField(Application)
    created_date = models.DateTimeField(default=now)
    already_checked = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    last_user_update = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='last_updated_user')

    def __str__(self):
        return '{}'.format(self.subject + ' | ' + '{}'.format(self.created_date))

    class Meta:
        permissions = (
            ('view_bajas_semanales_list', 'Visualize Bajas Semanales list'),
            ('create_baja_semanal', 'Create Baja Semanale'),
            ('update_baja_semanal', 'Update Bajas Semanales'),
        )

apps/bajas_semanales/api/v1/views.py
import io
import json
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import JSONParser
from rest_framework.views import APIView
from rest_framework import authentication, permissions
from rest_framework.response import Response

from django.db import transaction
from django.contrib import messages
from django.contrib.auth.models import User

from django.http import JsonResponse

from apps.application.models import Application
from apps.bajas_semanales.models import TipoBaja, BajaSemanal

from apps.bajas_semanales.api.v1.serializers import BajaSemanalSerializer


#no se usa
class GetSelectsData(APIView):

    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = []

    def get_tipo_bajas_data(self, request, **kwargs):

        data = {'success': True}
        try:
            tipo_bajas_list = []

            for t in TipoBaja.objects.filter(is_active=True):
                tipo_bajas_list.append({
                    "id": t.id,
                    "text": t.name
                })

            data = tipo_bajas_list
        except Exception as r:
            data['success'] = False
            data['message'] = 'Error: ', str(r)
        return Response(data)


class RecheckBaja(APIView):

    """
    Actualiza el campo de apps,
    Guarda un detalle del usuario que actualizó, y que campos/apps ha actualizado.
    """

    #authentication_classes = [authentication.TokenAuthentication]
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request, **kwargs):

        id = request.GET.get('id')
        print(id)
        detail = BajaSemanal.objects.get(uid=id)
        data = {'success': True}

        try:
            baja = []
            tipo_bajas_list = []
            app_list = []

            baja.append({
                "type": str(detail.type),
                "subject": detail.subject,
                "user_code": detail.user_code,
                "user_name": detail.user_name,
                "request_date": detail.request_date,
            })

            for t in TipoBaja.objects.filter(is_active=True):
                if t.id == detail.type.id:
                    tipo_bajas_list.append({
                        "id": t.id,
                        "text": t.type,
                        "selected": True,
                    })
                else:
                    tipo_bajas_list.append({
                        "id": t.id,
                        "text": t.type
                    })


            for x in detail.application.all():
                app_list.append({
                    "id": x.id,
                    "text": x.name,
                    "selected": True
                })
            for a in Application.objects.filter(is_active=True, is_for_bajas_semanales=True):
                if a.name not in [t['text'] for t in app_list]:
                    app_list.append({
                        "id": a.id,
                        "text": a.name,
                        "selected": False
                    })

            data['baja_semanal'] = baja
            data['tipo_bajas'] = tipo_bajas_list
            data['results'] = app_list
        except Exception as r:
            data['success'] = False
            data['message'] = 'Error: ', str(r)
        return Response(data)

    def post(self, request):

        data = {'success': True}
        try:
            if request.user.is_authenticated:

                update = BajaSemanal.objects.get(uid=request.POST.get('id'))

                type = request.POST.get('type')
                subject = request.POST.get('subject')
                user_code = request.POST.get('user_code')
                user_name = request.POST.get('user_name')
                request_date = request.POST.get('request_date')
                new_detail_app_list = request.POST.getlist('application[]')


                update.type=TipoBaja.objects.get(id=type)
                update.subject=subject
                update.user_code=user_code
                update.user_name=user_name
                update.request_date=request_date
                update.save()

                #Removing previous app to detail and adding new setted apps in detail.
                for a in update.application.all():
                    update.application.remove(a)
                for a in new_detail_app_list:
                    update.application.add(a)

                #Validate if detail app list has all required apps for bajas_semanales.
                #If so, can close record, if don´t, just kepps pending.
                a001_list = []
                for a in Application.objects.filter(is_active=True, is_for_bajas_semanales=True):
                    a001_list.append(a)
                if len(new_detail_app_list) > 0:
                    if len(new_detail_app_list) == len(a001_list):
                            update.already_checked = True

                update.last_user_update=User.objects.get(id=request.user.id)
                update.save()

                msg = 'Baja ' + update.user_code + ' updated successfully'
                msg_01 = 'Baja ' + update.user_code + ' already checked'
                messages.success(request, msg)

                data['updated'] = msg
                data['already_checked'] = msg_01
                data['current_detail_status'] = update.already_checked
            else:
                data['success'] = False
                data['message'] = 'Cannot identify authenticated user..'
        except Exception as t:
            data['success'] = False
            data['message'] = 'Error: ', str(t)
        return Response(data)

apps/bajas_semanales/views.py
import uuid

from django.shortcuts import render

from django.contrib import messages
from django.contrib.auth.models import User

from django.db import transaction

from django.urls import reverse_lazy

from django.utils import timezone

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView
from django.views.generic.edit import CreateView, View

from django.http import HttpResponseRedirect

from django.shortcuts import render

from apps.application.models import Application

from braces.views import LoginRequiredMixin

from apps.bajas_semanales.models import TipoBaja, BajaSemanal
from apps.bajas_semanales.forms import BajaSemanalForm, TipoBajaForm
from apps.bajas_semanales.filters import BajaSemanalFilter

from apps.tools.mixins import NeverCacheMixin, CSRFExemptMixin,\
 PermissionRequiredMixin

now = timezone.now()


class TipoBajaList(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, ListView):

    model = TipoBaja
    template_name = 'tipo_bajas_list.html'

    def get_context_data(self, **kwargs):
        context = super(TipoBajaList, self).get_context_data(**kwargs)
        context['tipo_bajas_list'] = True
        context['tipo_bajas'] = TipoBaja.objects.all()
        context['form'] = TipoBajaForm()
        context['count'] = TipoBaja.objects.all()
        return context


class CreateTipoBaja(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, CreateView):

    def get(self, request):

        context = {}
        context['new_tipo_baja'] = True
        context['form'] = TipoBajaForm()
        return render(request, 'bajas_semanales_form.html', context)

    @transaction.atomic
    def post(self, request):

        type = request.POST.get('type').title()

        if not TipoBaja.objects.filter(is_active=True, type=type):
            new = TipoBaja(
                type = type,
                created_date=now,
                is_active=True
            )
            new.save()
            msg = 'Tipo ' + new.type + ' saved successfully'
            messages.success(request, msg)
            return HttpResponseRedirect(reverse_lazy('bajas_semanales:tipo_bajas_list'))
        else:
            msg = 'Tipo ' + type + ' already exists, try with another one'
            messages.error(request, msg)
            return HttpResponseRedirect(reverse_lazy('bajas_semanales:create_tipo_baja'))


class BajasSemanalesList(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, ListView):

    model = BajaSemanal
    template_name = 'bajas_semanales_list.html'

    def get(self, request):

        #---Pagination begins---#
        bajas_list = BajaSemanal.objects.order_by('-created_date')
        bajas_filter = BajaSemanalFilter(request.GET, queryset=bajas_list)
        bajas_list = bajas_filter.qs

        page = request.GET.get('page')
        paginator = Paginator(bajas_list, 100)
        try:
            bajas_semanales_paginator = paginator.page(page)
        except PageNotAnInteger:
            bajas_semanales_paginator = paginator.page(1)
        except EmptyPage:
            bajas_semanales_paginator = paginator.page(paginator.num_pages)
        #---Pagination ends---#


        context = {}
        context['bajas_semanales_list'] = True
        #context['bajas_paginator'] = bajas_list #bajas_semanales_paginator
        #context['bajas_filter'] =

        context['paginator'] = paginator
        context['bajas_filter'] = bajas_filter
        context['bajas'] = bajas_semanales_paginator
        return render(request, 'bajas_semanales_list.html', context)


class CreateBajaSemanal(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, CreateView):

    """
    Crea registro y aplicaciones.
    Puede crear multiples usuarios con sus respectivos id, todos relacionados al
     subject del registro.

    """

    def get(self, request):

        context = {}
        user = request.user
        if not user.has_perm('bajas_semanales.create_baja_semanal'):
            return render(request, '404.html', context)
        else:
            context['new_baja_semanal'] = True
            context['form'] = BajaSemanalForm(request.GET)
            context['application_list'] = Application.objects.filter(
                                            is_active=True,
                                            is_for_bajas_semanales=True
                                         )

            return render(request, 'bajas_semanales_form.html', context)

    @transaction.atomic
    def post(self, request, *args):

        uid = str(uuid.uuid4()).replace('-', '')

        type = request.POST.get('type')
        subject = request.POST.get('subject')
        user_code = request.POST.get('user_code')
        user_name = request.POST.get('user_name')
        request_date = request.POST.get('request_date')
        application_list = request.POST.getlist('application')

        if not BajaSemanal.objects.filter(user_code=user_code, user_name=user_name):

            currnt_usr = User.objects.get(id=request.user.id)
            new  = BajaSemanal(
                uid = uid,
                type = TipoBaja.objects.get(id=type),
                subject = subject.title(),
                user_code = user_code.capitalize(),
                user_name = user_name.title(),
                request_date = request_date,
                created_date = now,
                user = currnt_usr,
                last_user_update = currnt_usr
            )
            new.save()

            for a in application_list:
                new.application.add(a)

            #Si el registro tiene todas las bajas marcar el "already checked"
            if new.application.all().count() == Application.objects.filter(
                                            is_active=True,
                                            is_for_bajas_semanales=True
                                        ).count():
                new.already_checked = True
                new.save()

            msg = 'Baja ' + subject + ' saved successfully'
            messages.success(request, msg)
            return HttpResponseRedirect(reverse_lazy('bajas_semanales:bajas_semanales_list'))
        else:
            messages.success(error, 'Username and user_id cannot be same')
            return HttpResponseRedirect(reverse_lazy('bajas_semanales:bajas_semanales_list'))


#Update es una API

apps/bajas_semanales/templates/bajas_semanales_form.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}


{% block title %}
    {% if new_baja_semanal %}
        New Baja Semanal
    {% elif update_baja_semanal %}
        Update Baja Semanal | {{ form.subject }}
    {% elif new_tipo_baja  %}
        New Tipo de Baja
    {% elif update_tipo_baja %}
        Update | {{ form.type }}
    {% endif %}
{% endblock %}

{% block extracss %}
    <link href="{% static 'css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                {{error.field}}
                <div class="alert alert-danger">
                    {{error|escape}}.
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger">
                {{message}}.
            </div>
        {% endfor %}
    {% endif %}

    <div class="wrapper wrapper-content animated fadeInUp">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            {% if new_baja_semanal %}
                                <h5>New Baja Semanal</h5>
                            {% elif update_baja_semanal %}
                                <h5>Update Baja - <strong>{{form.subject}}</strong></h5>
                            {% endif %}

                        </div>

                        <div class="ibox-content">
                            <form method="post" class="form-horizontal">{% csrf_token %}

                                <div class="form-group">
                                    <div class="col-lg-10">
                                        {% if new_tipo_baja or update_tipo_baja %}
                                          {{form.as_p}}
                                        {% elif new_baja_semanal or update_baja_semanal %}
                                          {{form.as_p}}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>

                                <div class="form-group">
                                    <div class="col-sm-4 col-sm-offset-2">
                                      {% if new_tipo_baja or update_tipo_baja %}
                                        <a class="btn btn-white" type="button" href="{% url 'bajas_semanales:tipo_bajas_list' %}">Cancel</a>
                                      {% elif new_baja_semanal or update_baja_semanal %}
                                          <a class="btn btn-white" type="button" href="{% url 'bajas_semanales:bajas_semanales_list' %}">Cancel</a>
                                      {% endif %}
                                        <button class="btn btn-primary" type="submit">Save changes</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
  <!-- Data picker -->
  <script src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>

  <script>

    $(document).ready(function(){

      var s_type = $('#id_type');
      var request_date = $('#id_request_date');
      var s_app = $('#id_application');


      request_date.datepicker({
          todayBtn: "linked",
          keyboardNavigation: false,
          forceParse: false,
          calendarWeeks: true,
          autoclose: true,
          format: 'yyyy-mm-dd'
      });

      s_app.addClass("form-control");
      s_app.select2({
        placeholder: "Select an application"
      });
      s_type.select2({
        placeholder: "Select a type"
      });


      //------------------------------------------------------
      request_date.on('keydown keyup keypress', function(){
          var $regexp = /^[_0-9]/;

          if (!$(this).val().match($regexp)){
            $(this).val('');
            //console.log('not match');
          }

    });



    });

  </script>

{% endblock %}

apps/bajas_semanales/templates/tipo_bajas_list.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Tipo de Bajas
{% endblock %}

{% block extracss %}
  <!-- FooTable -->
  <link href="{% static 'css/plugins/footable/footable.core.css' %}" rel="stylesheet">
  <link href="{% static 'css/plugins/select2/select2.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/plugins/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content">
          {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-success">
                      {{message}}.
                  </div>
              {% endfor %}
          {% endif %}

          <div class="row">
              <div class="col-lg-9">
                  <div class="wrapper wrapper-content animated fadeInUp">
                      <div class="ibox-title">
                          <h5> Tipos de Bajas Semanales </h5>
                          <div class="ibox-tools">
                              <a class="collapse-link">
                                  <i class="fa fa-chevron-up"></i>
                              </a>
                          </div>
                      </div>
                      <div class="ibox-content">
                          <div>
                            <br>
                            <br>
                            Total items:
                            <strong>{{ count.count }}</strong>
                          </div>
                          <div class="table-responsive">
                              <table class="table table-striped">
                                  <thead>
                                      <tr>
                                          <th>Type</th>
                                          <th>Created</th>
                                          <th>Active</th>
                                          {% if user.is_superuser %}
                                            <th>User</th>
                                          {% endif %}
                                      </tr>
                                  </thead>
                                  <tbody>
                                      {% for t in tipo_bajas %}
                                          <tr>
                                              <td>{{ t.type }}</td>
                                              <td>{{ t.created_date }}</td>
                                              {% if t.is_active %}
                                                <td>
                                                  <a href="#"><i class="fa fa-check"></i></a>
                                                </td>
                                              {% else %}
                                                <td>
                                                  <a href="#"><i class="fa fa-times"></i></a>
                                                </td>
                                              {% endif %}
                                              {% if user.is_superuser %}
                                                <td>{{ t.user }}</td>
                                              {% endif %}
                                          </tr>
                                      {% endfor %}
                                  </tbody>
                              </table>
                              Total items:
                              <strong>{{ count.count }}</strong>
                          </div>
                      </div>
                  </div>
              </div>
          </div>

    </div>
{% endblock %}

{% block extrajs %}
    <!-- FooTable -->
    <script src="{% static 'js/plugins/footable/footable.all.min.js' %}"></script>
    <!-- Select2 -->
    <script src="{% static 'js/plugins/select2/select2.full.min.js' %}"></script>
    <!-- Date range use moment.js same as full calendar plugin -->
    <script src="{% static 'js/plugins/fullcalendar/moment.min.js' %}"></script>
    <!-- Date range picker -->
    <script src="{% static 'js/plugins/daterangepicker/daterangepicker.js' %}"></script>

    <script>

        $(document).ready(function(){



        });
    </script>
{% endblock %}