apps/application/urls.py
from django.urls import path

from apps.application.views import ApplicationList, CreateApplication


urlpatterns = [
    path('list/', ApplicationList.as_view(), name='list'),
    path('new/', CreateApplication.as_view(), name='new'),    
]

voi/urls.py
from django.contrib import admin
from django.contrib.auth import authenticate

from django.urls import path, include

from django.apps import apps

from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import View

from braces.views import LoginRequiredMixin

from apps.tools.mixins import NeverCacheMixin, CSRFExemptMixin


application = apps.get_app_config('application').verbose_name
user = apps.get_app_config('user').verbose_name
bi_modules = apps.get_app_config('bi_modules').verbose_name
bajas_semanales = apps.get_app_config('bajas_semanales').verbose_name
zendesk = apps.get_app_config('zendesk').verbose_name
tools = apps.get_app_config('tools').verbose_name



class Dashboard(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, View):

    def get(self, request):
        #user = request.user
        context = {}
        context['dashboard'] = True
        return render(request, 'index.html', context)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('application/', include(('apps.application.urls', application), namespace='application')),
    path('bi_modules/', include(('apps.bi_modules.urls', bi_modules), namespace='bi_modules')),
    path('bajas/', include(('apps.bajas_semanales.urls', bajas_semanales), namespace='bajas_semanales')),
    path('zendesk/', include(('apps.zendesk.urls', zendesk), namespace='zendesk')),
    path('tools/', include(('apps.tools.urls', zendesk), namespace='tools')),

    path('api-auth/', include('rest_framework.urls')),
    path('bajas_semanales-api-v1/', include(('apps.bajas_semanales.api.v1.urls', bajas_semanales), namespace='bajas-semanales-api-v1')),
    path('bi_modules-api-v1/', include(('apps.bi_modules.api.v1.urls', bi_modules), namespace='bi_modules-api-v1')),
    path('zendesk-api-v1/', include(('apps.zendesk.api.v1.urls', zendesk), namespace='zendesk-api-v1')),
    path('tools-api-v1/', include(('apps.tools.api.v1.urls', tools), namespace='tools-api-v1')),
] + static(settings.STATIC_URL,
    document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

apps/application/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.tools.choices import TYPE, REGISTRY, INC_SOURCE, PAPERLESS, \
AMBASSADOR_TYPE, AEROPUERTOS, SK_ROLES, GSA


class Application(models.Model):
    """
    This model manage the normal and sox apps, each one with different parameters & rules
    """
    NORMAL = 'Normal'
    SOX = 'Sox'

    APP_TYPE = (
        ('NORMAL', NORMAL),
        ('SOX', SOX),
    )

    name = models.CharField(max_length=50, blank=False)
    registry_date = models.DateTimeField(auto_now_add=True)
    app_type = models.CharField(max_length=6, choices=APP_TYPE, default=NORMAL, blank=False)
    is_for_bajas_semanales = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, default='')

    def __str__(self):
        return self.name.capitalize()

    class Meta:
        permissions = (
            ('view_application_list', 'Can visualize the applications list'),
            ('create_application', 'Can create application'),
            ('update_application', 'Can update application'),
            ('disable_application', 'Can disable Application'),
        )

apps/application/forms.py
from django import forms

from apps.application.models import Application


class ApplicationForm(forms.ModelForm):

    is_for_bajas_semanales = forms.Select()

    class Meta:

        model = Application

        fields = [
            'name',
            'app_type',
            'is_for_bajas_semanales',
        ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'app_type': forms.Select(attrs={'class': 'form-control'}),
        }

apps/application/views.py
import datetime

from django.db import transaction

from django.contrib.auth.models import User

from django.contrib.auth import authenticate
from django.contrib import messages

from django.http import HttpResponseRedirect

from django.shortcuts import render

from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, View
from django.views.generic.list import ListView

from apps.application.models import Application
from apps.application.forms import ApplicationForm

from apps.applicant.models import Applicant

from apps.tools.mixins import NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin

now = datetime.datetime.now()

class ApplicationList(NeverCacheMixin, CSRFExemptMixin, View):

    model = Application
    template_name='list.html'
    paginate_by = 3  # if pagination is desired, not working for now.

    def get(self, request):

        user = request.user

        if user.has_perm('application.view_application_list') or \
            user.has_perm('applicant.view_applicant_list'):

            context = {}
            context['app_list'] = True
            context['applications'] = Application.objects.filter(is_active=True)
            context['applicants'] = Applicant.objects.filter(is_active=True)
            return render(request, 'list.html', context)
        else:
            return render(request, '404.html')

class CreateApplication(NeverCacheMixin, CSRFExemptMixin, LoginRequiredMixin, View):


    def get(self, request):

        user = request.user

        if not user.has_perm('application.create_application'):
            return render(request, '404.html')
        else:
            context = {}
            context["new_app"] = True
            context['form'] = ApplicationForm
            return render(request, 'application_form.html', context)

    @transaction.atomic
    def post(self, request):

        name = request.POST.get('name').upper()
        app_type = request.POST.get('app_type')
        is_for_bajas_semanales = request.POST.get('is_for_bajas_semanales')

        if Application.objects.filter(is_active=True, name=name):

            msg = 'Application name ' + name + ' already exist!'
            messages.error(request, msg)
            return HttpResponseRedirect(reverse_lazy('application:new'))
        else:

            if is_for_bajas_semanales == 'on':
                is_for_bajas_semanales = True
            elif not is_for_bajas_semanales:
                is_for_bajas_semanales = False

            new_app = Application(
                name=name,
                registry_date=now,
                app_type=app_type,
                is_for_bajas_semanales=is_for_bajas_semanales,
                is_active=True,
                user=User.objects.get(id=request.user.id)
            )
            new_app.save()

            msg = 'Application ' + name + ' saved successfully'
            messages.success(request, msg)

            user = request.user

            if not user.has_perm('application.view_application_list'): #and \
                #user.has_perm('applicant.view_applicant_list'):
                    return HttpResponseRedirect(reverse_lazy('dashboard'))
            else:
                return HttpResponseRedirect(reverse_lazy('application:list'))

apps/application/templates/application_form.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    {% if new_app %}
        New Application
    {% elif update_app %}
        Update Application
    {% endif %}
{% endblock %}

{% block content %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                {{error.field}}
                <div class="alert alert-danger">
                    {{error|escape}}.
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    {% if messages %}
        {% for message in messages %}

            <div class="alert alert-danger">
                {{message}}.
            </div>
        {% endfor %}
    {% endif %}

    <div class="wrapper wrapper-content animated fadeInUp">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            {% if new_app %}
                                <h5>New <small>Application</small></h5>
                            {% elif update_app %}
                                <h5>Update current <small>Application</small></h5>
                            {% endif %}

                        </div>

                        <div class="ibox-content">
                            <form method="post" class="form-horizontal">{% csrf_token %}

                                <div class="form-group"><label class="col-sm-2 control-label">Name</label>

                                    <div class="col-sm-10">
                                        {{ form.name }}
                                    </div>
                                </div>
                                <div class="form-group"><label class="col-sm-2 control-label">Application Type</label>

                                    <div class="col-sm-10">
                                        {{ form.app_type }}
                                    </div>
                                </div>
                                <div class="form-group"><label class="col-sm-2 control-label">Is for Bajas Semanales?</label>

                                    <div class="col-sm-10">
                                        {{ form.is_for_bajas_semanales }}
                                    </div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group">
                                    <div class="col-sm-4 col-sm-offset-2">
                                        <a class="btn btn-white" type="button" href="{% url 'Application:list' %}">Cancel</a>
                                        <button class="btn btn-primary" type="submit">Save changes</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script>
        $(document).ready(function(){
           var s_app_type = $('#id_app_type');

           s_app_type.select2();
        });
    </script>
{% endblock %}

apps/application/templates/list.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Application List
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content">
        <div class="container">

            {% if messages %}
                {% for message in messages %}

                    <div class="alert alert-success">
                        {{message}}.
                    </div>
                {% endfor %}
            {% endif %}

            <div class="row">
                {% if perms.application.view_application_list %}
                    <div class="col-lg-12">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h5> Application List </h5>
                                <div class="ibox-tools">
                                    <a class="collapse-link">
                                        <i class="fa fa-chevron-up"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="ibox-content">
                                <div class="row">
                                <div class="col-sm-9 m-b-xs">

                                    </div>
                                    <!--
                                    <div class="col-sm-3">
                                        <div class="input-group"><input type="text" placeholder="Search" class="input-sm form-control"> <span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary"> Go!</button> </span></div>
                                    </div>
                                    -->
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped" id="yes">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Application Type</th>
                                                <th>Reg Date </th>
                                                {% if user.is_superuser %}
                                                    <th>User </th>
                                                {% endif %}
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for app in applications %}
                                                <tr>
                                                    <td>{{ app.name }}</td>
                                                    <td>{{ app.app_type}}</td>
                                                    <td>{{ app.registry_date }}</td>
                                                    {% if user.is_superuser %}
                                                        <th>{{ app.user }} </th>
                                                    {% endif %}
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>

    <script>

        $(document).ready(function(){
            $('.table').DataTable({
                pageLength: 10,
                responsive: true,
                /*dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    {
                        extend: 'copy'
                    },
                    {
                        extend: 'csv', title: 'History'
                    },
                ]*/

            });


        });

    </script>
{% endblock %}